apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: vcenter-vm-second-nic
  namespace: default
spec:
  config: '{
    "cniVersion": "0.3.1",
    "plugins": [
    {
    "type": "macvlan",
    "master": "eth1",
    "mode": "bridge",
    "ipam": {
      "type": "dhcp"
    }}
    ]
    }'
 
