apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: vcenter-vm-second-nic
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
    seccompProfile:
      type: RuntimeDefault
    runAsNonRoot: true
  containers:
  - name: sample-pod
    #    image: harbor-repo.vmware.com/dockerhub-proxy-cache/library/busybox:1.28
    #    command: [ "sh", "-c", "sleep 1h" ]
    image: projects-stg.registry.vmware.com/tkg-test-infra/netshoot:v0.11
    command: ["/bin/sleep", "10000"]
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
